### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by Philipinho**

### CODE REVIEW

**Comment by christroutner** [comment]
@GitCash send $1 to @Philipinho

**Comment by GitCash** [comment]
Hey **Philipinho**, user **christroutner** tipped you **7812 bits** in Bitcoin Cash ( ~ **$1** ).

*[Click here to claim it!](https://gitcash.io/claim/Philipinho)*

You can also add the "thumbs down" reaction to **christroutner**'s comment above to prevent future tips.

**Comment by christroutner** [comment]
@GitCash send $1 to @Philipinho

**Comment by christroutner** [comment]
Thank you!

**Comment by Philipinho** [comment]
Thanks for the tip.

**Pull request merged**
